#!/bin/bash

clear

if [ `id -u` != 0 ]; then # Is root?

  echo -e '\033[1;31mYou need to be root to perform this action.\033[0m\n'
  exit 1

fi

if [ ! `which dialog` ]; then
  apt-get install -y dialog
fi

TITLE="Ubuntu Apps Installer"
USER_NAME=$SUDO_USER
USER_HOME=/home/$USER_NAME
DOWNLOADS=~/Downloads
OS_NAME=`lsb_release -i | sed 's/Distributor ID:\t//g'`
OS_VERSION=`lsb_release -r | sed 's/Release:\t//g'`

if [ $OS_NAME != "Ubuntu" ]; then

  echo -e '\033[1;31mThis operating system is not supported.\033[0m\n'
  exit 1

fi

source apps

# DIALOG #######################################################################
cmd=(dialog --backtitle "$TITLE" --separate-output --checklist "Select apps to install:" 30 140 23)

options=(
  01 "Utils (g++, make, build-essential, curl, tree, vim, whois, sshfs, httpie, ntp, zip, unzip)" off
  02 "Ubuntu Restricted Extras"                                                                   off
  03 "Top (htop, iftop, iotop)"                                                                   off
  04 "Unity Tweak Tool"                                                                           off
  05 "Node.js"                                                                                    off
  06 "Node.js Version Manager"                                                                    off
  07 "Node.js Packages (grunt-cli, gulp-cli, bower, npm-check-updates, gitignore)"                off
  08 "Python"                                                                                     off
  09 "The Fuck (Requires Python)"                                                                 off
  10 "Ruby"                                                                                       off
  11 "Ruby Packages (sass, scss-lint, rhc)"                                                       off
  12 "nginx"                                                                                      off
  13 "Apache2"                                                                                    off
  14 "PHP5 (cli, curl, dev, fpm, gd, mcrypt, memcache, xdebug...)"                                off
  15 "Composer"                                                                                   off
  16 "MySQL"                                                                                      off
  17 "MySQL Workbench"                                                                            off
  18 "PostgreSQL"                                                                                 off
  19 "pgAdmin"                                                                                    off
  20 "MongoDB"                                                                                    off
  21 "MongoChef"                                                                                  off
  22 "Sublime Text"                                                                               off
  23 "DropBox"                                                                                    off
  24 "ownCloud"                                                                                   off
  25 "Mega"                                                                                       off
  26 "Google Chrome"                                                                              off
  27 "TimeShift"                                                                                  off
  28 "ScreenCloud"                                                                                off
  29 "KeePass X"                                                                                  off
  30 "Reset MS Mice (Fixes Abnormal Scroll Wheel Problems with Certain Microsoft Mice)"           off
  31 "Ajenti"                                                                                     off
  32 "Webmin"                                                                                     off
  33 "Spotify"                                                                                    off
  34 "uGet Download Manager"                                                                      off
  35 "MS and OSX fonts"                                                                           off
  36 "Diff tools (Diffuse, Meld)"                                                                 off
  37 "VirtualBox"                                                                                 off
  38 "Vagrant (Requires VirtualBox)"                                                              off
  39 "Homestead (Requires Vagrant)"                                                               off
  40 "Java"                                                                                       off
  41 "Apache Maven"                                                                               off
  42 "NetBeans"                                                                                   off
  43 "Android Studio"                                                                             off
  44 "Microsoft Visual Studio Code"                                                               off
  45 "TexLive"                                                                                    off
  46 "Texmaker"                                                                                   off
  47 "Kazam Screencaster"                                                                         off
  48 "Skype"                                                                                      off
  49 "Viber"                                                                                      off
  50 "Nylas N1"                                                                                   off
  51 "Brave"                                                                                      off
  52 "Yandex Disk"                                                                                off
  53 "Yumi"                                                                                       off
  54 "Steam"                                                                                      off
  55 "JetBrains Toolbox App"                                                                      off
  56 "Open365"                                                                                    off
  57 "MEO Cloud"                                                                                  off
  58 "Genymotion"                                                                                 off
  59 "ZSH"                                                                                        off
  60 "TeamViewer"                                                                                 off
  61 "Ruby Version Manager"                                                                       off
  62 "System Load Indicator"                                                                      off
  63 "Git Flow"                                                                                   off
  64 "Git Journal"                                                                                off
  65 "Poedit"                                                                                     off
  66 "rustup"                                                                                     off
  67 "Heroku Command Line"                                                                        off
  68 "Yarn (Node.js Dependency Management)"                                                       off
  69 "System Update"                                                                              on
  70 "Restart system after install"                                                               off
)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

clear

apt-get update

for choice in $choices; do

  case $choice in

    01) utilsInstaller               ;;
    02) restrictedExtrasInstaller    ;;
    03) topInstaller                 ;;
    04) unityTweakInstaller          ;;
    05) nodeJSInstaller              ;;
    06) nvmInstaller                 ;;
    07) nodeJSPackagesInstaller      ;;
    08) pythonInstaller              ;;
    09) theFuckInstaller             ;;
    10) rubyInstaller                ;;
    11) rubyPackagesInstaller        ;;
    12) nginxInstaller               ;;
    13) apacheInstaller              ;;
    14) phpInstaller                 ;;
    15) composerInstaller            ;;
    16) mysqlInstaller               ;;
    17) mysqlWorkbenchInstaller      ;;
    18) postgresInstaller            ;;
    19) pgAdminInstaller             ;;
    20) mongoDBInstaller             ;;
    21) mongoCheffInstaller          ;;
    22) sublimeTextInstaller         ;;
    23) dropboxInstaller             ;;
    24) ownCloudInstaller            ;;
    25) megaInstaller                ;;
    26) chromeInstaller              ;;
    27) timeShiftInstaller           ;;
    28) screenCloudInstaller         ;;
    29) keePassXInstaller            ;;
    30) resetMsMiceInstaller         ;;
    31) ajentiInstaller              ;;
    32) webminInstaller              ;;
    33) spotifyInstaller             ;;
    34) ugetInstaller                ;;
    35) fontsInstaller               ;;
    36) diffToolsInstaller           ;;
    37) virtualBoxInstaller          ;;
    38) vagrantInstaller             ;;
    39) homesteadInstaller           ;;
    40) javaInstaller                ;;
    41) mavenInstaller               ;;
    42) netbeansInstaller            ;;
    43) androidStudioInstaller       ;;
    44) visualStudioCodeInstaller    ;;
    45) texliveInstaller             ;;
    46) texmakerInstaller            ;;
    47) kazamScreencasterInstaller   ;;
    48) skypeInstaller               ;;
    49) viberInstaller               ;;
    50) nylasN1Installer             ;;
    51) braveInstaller               ;;
    52) yandexDiskInstaller          ;;
    53) yumiInstaller                ;;
    54) steamInstaller               ;;
    55) jetBrainsToolboxAppInstaller ;;
    56) open365Installer             ;;
    57) meoCloudInstaller            ;;
    58) genymotionInstaller          ;;
    59) zshInstaller                 ;;
    60) teamViewerInstaller          ;;
    61) rvmInstaller                 ;;
    62) systemLoadIndicatorInstaller ;;
    63) gitFlowInstaller             ;;
    64) gitJournalInstaller          ;;
    65) poeditInstaller              ;;
    66) rustupInstaller              ;;
    67) toolbeltInstaller            ;;
    68) yarnInstaller                ;;
    69) systemUpdate                 ;;
    70) restart                      ;;

  esac

done

apt-get install -f

dialog --backtitle "$TITLE" --msgbox "Your apps were installed o/" 12 30

clear
